name: Execução de testes regressivos
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 9,11,15,18 * * 0,1,2,3,4,5,6'
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout projeto
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install

    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1

    - name: Run CodeceptJS tests
      run: npx codeceptjs test

  